"""Tests for `physiclaw.agent.engine.job_store` — durable job model.

Two infrastructure pieces:

  - `tmp_path` for the jobs.md file. Tests pass an explicit `path`
    argument to every entry point; the default `JOBS_PATH` is
    captured at import time and isn't reliable per-test.
  - `freezegun` for time-dependent code: `matches_now`, `next_fire`,
    `purge_stale`, `find_due`. Where a test pre-builds a `Job` with
    a fixed timestamp, we don't need freezegun — only when the
    function reads `dt.datetime.now()` internally.

Job-section text is generated by a helper so each test only varies the
field under test. The `_PURGE_AFTER` window comes from
`CONFIG.retention.trace_days` (default 7); tests that depend on the
boundary monkeypatch the module attribute to a known value.

Accepted equivalent / unreachable mutants (cannot be killed by
behavior tests at the module's public surface):

  - `_NEVER_VALUES = {"", …}` ↔ `{"XXXX", …}` — the empty-string member
    is unreachable: post-strip field values are either nonempty or
    one of the (never)-ish literals; "" never appears in input.
  - `body = parts[i+1] if i+1 < len(parts) else ""` mutations
    (i+1<len → i-1<len, i+1<=len, else "XXXX") — the else branch is
    dead code because `re.split` with a capturing group always returns
    a list of length 2n+1; the loop's last `i+1` is `len-1 < len`.
  - `description = ""` ↔ `None` / `start = 0` ↔ `None` — both are
    overwritten before use along every code path that depends on them.
  - `return "", {}` ↔ `return "XXXX", {}` — caller checks
    `if not fields:`, the description is dropped on the empty-fields
    path.
  - `subn(..., count=1)` ↔ `count=2` — a job section has at most one
    match for any field name; both produce the same output.
  - `strip("`")` ↔ `strip("XX`XX")` — schedule values don't contain
    X characters at the edges.
  - `_latest_timestamp` ValueError `continue` ↔ `break` — only two
    fields are tried; both control flows reach the post-loop
    `return None` with identical state.
  - `now.replace(second=0, microsecond=0)` ↔ `second=1` /
    `microsecond=1` (matches_now) — `croniter.match` operates at
    minute granularity and ignores sub-minute fields entirely.
  - `t.replace(second=0, microsecond=0).isoformat(timespec="minutes")`
    mutations — `timespec="minutes"` truncates to HH:MM regardless of
    second/microsecond values.
  - `re.sub(r"\\n{3,}", "\\n\\n", text)` mutations on the cleanup
    regex — the section-removal regex is non-greedy and consumes all
    inter-section whitespace up to the next heading, so post-removal
    text never actually contains triple+ blank lines and the cleanup
    is defensive only.
"""
from __future__ import annotations

import datetime as dt
import re
from pathlib import Path
from textwrap import dedent

import pytest
from freezegun import freeze_time

from physiclaw.agent.engine import job_store
from physiclaw.agent.engine.job_store import (
    KIND_PERIODIC,
    NEVER,
    STATUS_CANCEL,
    STATUS_DONE,
    STATUS_FAIL,
    STATUS_FIRED,
    STATUS_PEND,
    TERMINAL_STATUSES,
    Job,
    find_due,
    format_minute,
    load_jobs,
    matches_now,
    next_fire,
    purge_stale,
    update_fields,
    validate_schedule,
)


# ---------- helpers ----------


def _job_section(
    *,
    job_id: str = "user-greet-2026-04-28",
    description: str = "Say good morning to the user",
    kind: str = "periodic",
    status: str = "pend",
    schedule: str = "0 7 * * *",
    context: str = "ten char minimum context",
    create_time: str = "2026-04-28T07:00",
    next_fire_time: str = "2026-04-29T07:00",
    last_fire_time: str = NEVER,
    execution_time: str = NEVER,
    execution_result: str = NEVER,
) -> str:
    return dedent(
        f"""\
        ## {job_id}
        {description}
        - Type: {kind}
        - Status: {status}
        - Schedule: `{schedule}`
        - Context: {context}
        - Create time: {create_time}
        - Next fire time: {next_fire_time}
        - Last fire time: {last_fire_time}
        - Execution time: {execution_time}
        - Execution result: {execution_result}
        """
    )


def _write_jobs(tmp_path: Path, *sections: str, header: str = "") -> Path:
    p = tmp_path / "jobs.md"
    p.write_text((header + "\n" if header else "") + "\n".join(sections))
    return p


# ---------- protocol constants ----------


@pytest.mark.parametrize(
    "name, expected",
    [
        ("KIND_PERIODIC", "periodic"),
        ("KIND_ONE_TIME", "one-time"),
        ("STATUS_PEND", "pend"),
        ("STATUS_FIRED", "fired"),
        ("STATUS_CANCEL", "cancel"),
        ("STATUS_DONE", "done"),
        ("STATUS_FAIL", "fail"),
        ("NEVER", "(never)"),
    ],
)
def test_protocol_constant_pinned(name: str, expected: str) -> None:
    assert getattr(job_store, name) == expected


def test_terminal_statuses_set_is_cancel_done_fail_only() -> None:
    assert TERMINAL_STATUSES == frozenset({STATUS_CANCEL, STATUS_DONE, STATUS_FAIL})


# ---------- Job dataclass ----------


def test_job_is_frozen() -> None:
    j = Job(id="x", kind="periodic", schedule="* * * * *", description="d")

    with pytest.raises(Exception):  # FrozenInstanceError
        j.id = "y"  # type: ignore[misc]


def test_job_defaults_are_pend_with_empty_optional_fields() -> None:
    j = Job(id="x", kind="periodic", schedule="* * * * *", description="d")

    assert j.status == STATUS_PEND
    assert j.context == ""
    assert j.next_fire_time == ""
    assert j.last_fire_time == ""
    assert j.execution_time == ""
    assert j.execution_result == ""


# ---------- load_jobs: file existence ----------


def test_load_jobs_returns_empty_when_file_missing(tmp_path: Path) -> None:
    assert load_jobs(tmp_path / "missing.md") == []


def test_load_jobs_returns_empty_for_empty_file(tmp_path: Path) -> None:
    p = tmp_path / "jobs.md"
    p.write_text("")

    assert load_jobs(p) == []


def test_load_jobs_returns_empty_when_only_documentation_section(
    tmp_path: Path,
) -> None:
    # heading not matching ID_RE → silently skipped, no fields → not a job.
    p = tmp_path / "jobs.md"
    p.write_text("## How To Use\n\nFree-form notes here.\n")

    assert load_jobs(p) == []


def test_load_jobs_skips_section_with_valid_id_but_only_a_description(
    tmp_path: Path,
) -> None:
    # Heading matches ID_RE but body has no recognized fields — treated as
    # documentation, silently skipped.
    p = tmp_path / "jobs.md"
    p.write_text("## job-id\nJust a description, no fields here.\n")

    assert load_jobs(p) == []


def test_load_jobs_skips_section_with_no_body_lines(tmp_path: Path) -> None:
    # Heading immediately followed by another heading — empty body, no
    # fields, skipped.
    p = tmp_path / "jobs.md"
    p.write_text("## empty-one\n## empty-two\n")

    assert load_jobs(p) == []


def test_load_jobs_uses_module_JOBS_PATH_when_path_argument_omitted() -> None:
    # JOBS_PATH was captured at import time; without a real file there,
    # the function returns [] safely.
    assert load_jobs() == []


# ---------- load_jobs: happy paths ----------


def test_load_jobs_parses_a_single_well_formed_job(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section())

    jobs = load_jobs(p)

    assert len(jobs) == 1
    job = jobs[0]
    assert job.id == "user-greet-2026-04-28"
    assert job.kind == KIND_PERIODIC
    assert job.schedule == "0 7 * * *"
    assert job.description == "Say good morning to the user"
    assert job.context == "ten char minimum context"
    assert job.next_fire_time == "2026-04-29T07:00"
    assert job.last_fire_time == ""  # NEVER → ""
    assert job.execution_time == ""
    assert job.execution_result == ""


def test_load_jobs_parses_multiple_jobs(tmp_path: Path) -> None:
    p = _write_jobs(
        tmp_path,
        _job_section(job_id="job-a-2026-04-28"),
        _job_section(job_id="job-b-2026-04-28"),
    )

    jobs = load_jobs(p)

    assert [j.id for j in jobs] == ["job-a-2026-04-28", "job-b-2026-04-28"]


def test_load_jobs_normalizes_NEVER_value_variants_to_empty_string(
    tmp_path: Path,
) -> None:
    # `_NEVER_VALUES` includes "", NEVER, "never", "-".
    section = _job_section(
        last_fire_time="never",
        execution_time="-",
        execution_result="(never)",
    )
    p = _write_jobs(tmp_path, section)

    job = load_jobs(p)[0]

    assert job.last_fire_time == ""
    assert job.execution_time == ""
    assert job.execution_result == ""


def test_load_jobs_ignores_non_id_documentation_section_alongside_real_jobs(
    tmp_path: Path,
) -> None:
    p = _write_jobs(
        tmp_path,
        "## How To Use\n\nFree-form docs.\n",
        _job_section(),
    )

    jobs = load_jobs(p)

    assert len(jobs) == 1
    assert jobs[0].id == "user-greet-2026-04-28"


# ---------- load_jobs: error families ----------


def test_load_jobs_raises_on_duplicate_id(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section(), _job_section())

    with pytest.raises(ValueError, match=r"^duplicate job id: 'user-greet-2026-04-28'$"):
        load_jobs(p)


def test_load_jobs_raises_when_description_missing(tmp_path: Path) -> None:
    section = _job_section()
    # Strip the description line — leave only the heading and fields.
    lines = section.splitlines(keepends=True)
    section = lines[0] + "".join(lines[2:])
    p = _write_jobs(tmp_path, section)

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: missing description line below the heading$",
    ):
        load_jobs(p)


def test_load_jobs_raises_on_invalid_kind(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section(kind="hourly"))

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: Type must be 'periodic' or 'one-time', got 'hourly'$",
    ):
        load_jobs(p)


def test_load_jobs_raises_on_invalid_status(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section(status="weird"))

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: Status must be one of .+, got 'weird'$",
    ):
        load_jobs(p)


def test_load_jobs_raises_on_invalid_cron_schedule(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section(schedule="not a cron"))

    with pytest.raises(ValueError, match=r"^invalid cron expression"):
        load_jobs(p)


def test_load_jobs_raises_on_short_context(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section(context="short"))  # < 10 chars

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: Context too short \(min 10 chars\)$",
    ):
        load_jobs(p)


def test_load_jobs_accepts_context_at_exactly_10_characters(tmp_path: Path) -> None:
    # `len(context) < 10` — exactly 10 must pass. `<= 10` mutation
    # would reject this; `< 11` mutation would also reject (treats 10
    # as too short).
    p = _write_jobs(tmp_path, _job_section(context="x" * 10))

    jobs = load_jobs(p)

    assert len(jobs) == 1
    assert jobs[0].context == "x" * 10


def test_load_jobs_raises_when_pend_job_has_no_next_fire_time(
    tmp_path: Path,
) -> None:
    p = _write_jobs(tmp_path, _job_section(status="pend", next_fire_time=NEVER))

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: Next fire time is required for pend jobs$",
    ):
        load_jobs(p)


def test_load_jobs_raises_when_pend_next_fire_time_is_not_iso(
    tmp_path: Path,
) -> None:
    p = _write_jobs(
        tmp_path, _job_section(status="pend", next_fire_time="not a timestamp")
    )

    with pytest.raises(
        ValueError, match=r"is not a valid ISO timestamp"
    ):
        load_jobs(p)


def test_load_jobs_raises_when_next_fire_time_does_not_match_schedule(
    tmp_path: Path,
) -> None:
    # schedule fires at minute 0, next_fire_time is at minute 30.
    p = _write_jobs(
        tmp_path,
        _job_section(
            status="pend",
            schedule="0 * * * *",
            next_fire_time="2026-04-29T07:30",
        ),
    )

    with pytest.raises(
        ValueError, match=r"does not match Schedule"
    ):
        load_jobs(p)


def test_load_jobs_raises_on_unexpected_line_in_section(tmp_path: Path) -> None:
    section = _job_section() + "- Garbage: extra line\n"
    p = _write_jobs(tmp_path, section)

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: unexpected line: '- Garbage: extra line'$",
    ):
        load_jobs(p)


def test_load_jobs_raises_on_missing_required_field(tmp_path: Path) -> None:
    section = _job_section()
    # Drop the "Status" line.
    section = re.sub(r"^- Status:.*\n", "", section, flags=re.MULTILINE)
    p = _write_jobs(tmp_path, section)

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: missing required field\(s\): Status$",
    ):
        load_jobs(p)


def test_load_jobs_raises_with_comma_separated_list_when_multiple_fields_missing(
    tmp_path: Path,
) -> None:
    # Multi-field message uses ', '.join; mutant that wraps the join
    # separator only shows when at least 2 fields are missing.
    section = _job_section()
    section = re.sub(
        r"^- (Status|Schedule):.*\n", "", section, flags=re.MULTILINE
    )
    p = _write_jobs(tmp_path, section)

    with pytest.raises(
        ValueError,
        match=r"^user-greet-2026-04-28: missing required field\(s\): Schedule, Status$",
    ):
        load_jobs(p)


def test_load_jobs_continues_past_documentation_section_to_a_real_job(
    tmp_path: Path,
) -> None:
    # `if not fields: continue` — `break` would stop iteration and the
    # later real job wouldn't be parsed.
    p = _write_jobs(
        tmp_path,
        "## docs-section\nDocs only, no fields.\n",
        _job_section(),
    )

    jobs = load_jobs(p)

    assert len(jobs) == 1
    assert jobs[0].id == "user-greet-2026-04-28"


def test_load_jobs_handles_heading_at_eof_without_trailing_body(
    tmp_path: Path,
) -> None:
    # Trailing heading with no body — `re.split` produces an even-length
    # list, so the `body = parts[i+1] if i+1 < len else ""` else-branch
    # fires and must yield an empty string (mutations would IndexError
    # or substitute a placeholder body).
    p = tmp_path / "jobs.md"
    p.write_text("## empty-end")

    assert load_jobs(p) == []


def test_load_jobs_accepts_non_pend_with_invalid_iso_only_when_empty(
    tmp_path: Path,
) -> None:
    # done/fail/cancel can leave next_fire_time empty (NEVER) — accepted.
    p = _write_jobs(tmp_path, _job_section(status="done", next_fire_time=NEVER))

    job = load_jobs(p)[0]

    assert job.status == STATUS_DONE
    assert job.next_fire_time == ""


def test_load_jobs_raises_on_done_job_with_malformed_next_fire_time(
    tmp_path: Path,
) -> None:
    # If a non-pend job DOES have a next_fire_time set, it must still
    # be a valid ISO timestamp (even though the cron-match check is
    # skipped).
    p = _write_jobs(
        tmp_path, _job_section(status="done", next_fire_time="not iso")
    )

    with pytest.raises(ValueError, match=r"is not a valid ISO timestamp"):
        load_jobs(p)


# ---------- validate_schedule ----------


@pytest.mark.parametrize(
    "schedule",
    ["* * * * *", "0 7 * * *", "*/5 * * * *", "0 9-17 * * 1-5", "30 14 1 1 *"],
)
def test_validate_schedule_accepts_valid_cron(schedule: str) -> None:
    validate_schedule(schedule)  # no raise


@pytest.mark.parametrize(
    "schedule",
    ["not cron", "* *", "0 25 * * *", "60 * * * *", ""],
)
def test_validate_schedule_raises_on_invalid_cron(schedule: str) -> None:
    with pytest.raises(ValueError, match=r"^invalid cron expression"):
        validate_schedule(schedule)


# ---------- matches_now ----------


def test_matches_now_returns_true_when_minute_is_a_match() -> None:
    assert matches_now("30 14 * * *", dt.datetime(2026, 4, 28, 14, 30)) is True


def test_matches_now_returns_false_when_minute_is_not_a_match() -> None:
    assert matches_now("30 14 * * *", dt.datetime(2026, 4, 28, 14, 31)) is False


def test_matches_now_strips_nonzero_seconds_to_zero_before_match() -> None:
    # The replace(second=0, microsecond=0) is what lets a 14:30:45 wall
    # clock match a "30 14 * * *" cron. Mutating second=0 to second=1
    # leaves seconds nonzero, but croniter still rounds down to the
    # minute — same outcome. The detectable case: a moment whose second
    # value would, if not zeroed, push it past the minute boundary.
    moment = dt.datetime(2026, 4, 28, 14, 30, 45)

    assert matches_now("30 14 * * *", moment) is True


def test_matches_now_strips_microseconds_before_match() -> None:
    moment = dt.datetime(2026, 4, 28, 14, 30, 0, 999_999)

    assert matches_now("30 14 * * *", moment) is True


# ---------- next_fire ----------


def test_next_fire_returns_next_minute_match_after_given_time() -> None:
    # Schedule fires every hour at :00; from 14:30, next is 15:00.
    nxt = next_fire("0 * * * *", dt.datetime(2026, 4, 28, 14, 30))

    assert nxt == dt.datetime(2026, 4, 28, 15, 0)


# ---------- format_minute ----------


def test_format_minute_truncates_seconds_to_exactly_zero() -> None:
    # Result is "...HH:MM" (no seconds component) — second/microsecond
    # mutations would surface as a different time string only when the
    # input has nonzero values. Use both nonzero so both replace() args
    # are exercised.
    out = format_minute(dt.datetime(2026, 4, 28, 14, 30, 45, 999_999))

    assert out == "2026-04-28T14:30"


def test_format_minute_input_with_zero_seconds_returns_same_minute_string() -> None:
    # Sanity: when input is already minute-aligned, output matches.
    out = format_minute(dt.datetime(2026, 4, 28, 14, 30, 0, 0))

    assert out == "2026-04-28T14:30"


# ---------- find_due ----------


def test_find_due_returns_pend_jobs_at_or_before_now() -> None:
    now = dt.datetime(2026, 4, 28, 12, 0)
    due_job = Job(
        id="due", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="2026-04-28T11:30",
    )
    future_job = Job(
        id="future", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="2026-04-28T13:00",
    )

    assert find_due([due_job, future_job], now) == [due_job]


def test_find_due_at_exact_minute_includes_the_job() -> None:
    now = dt.datetime(2026, 4, 28, 12, 0)
    job = Job(
        id="j", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="2026-04-28T12:00",
    )

    # `<= now` — exact minute is due.
    assert find_due([job], now) == [job]


def test_find_due_skips_non_pend_jobs() -> None:
    now = dt.datetime(2026, 4, 28, 12, 0)
    fired = Job(
        id="f", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        status=STATUS_FIRED,
        next_fire_time="2026-04-28T11:30",
    )
    done = Job(
        id="d", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        status=STATUS_DONE,
        next_fire_time="2026-04-28T11:30",
    )

    assert find_due([fired, done], now) == []


def test_find_due_skips_pend_with_empty_next_fire_time() -> None:
    now = dt.datetime(2026, 4, 28, 12, 0)
    job = Job(
        id="x", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="",
    )

    assert find_due([job], now) == []


def test_find_due_skips_pend_with_unparseable_iso_timestamp() -> None:
    now = dt.datetime(2026, 4, 28, 12, 0)
    job = Job(
        id="x", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="not iso",
    )

    assert find_due([job], now) == []


def test_find_due_continues_past_skipped_jobs_to_collect_later_due_ones() -> None:
    # Each `continue` in find_due must NOT be a `break` — a non-pend
    # job, an empty-next_fire_time pend job, and a malformed-iso pend
    # job all sit AHEAD of a real due job in the list. Break would
    # short-circuit and miss the due job.
    now = dt.datetime(2026, 4, 28, 12, 0)
    skipped_status = Job(
        id="a", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        status=STATUS_FIRED, next_fire_time="2026-04-28T11:00",
    )
    skipped_no_time = Job(
        id="b", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="",
    )
    skipped_bad_iso = Job(
        id="c", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="not iso",
    )
    real_due = Job(
        id="due", kind=KIND_PERIODIC, schedule="* * * * *", description="d",
        next_fire_time="2026-04-28T11:00",
    )

    out = find_due([skipped_status, skipped_no_time, skipped_bad_iso, real_due], now)

    assert out == [real_due]


# ---------- update_fields ----------


def test_update_fields_replaces_named_field_value(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section(status="pend"))

    update_fields(p, {"user-greet-2026-04-28": {"Status": "fired"}})

    text = p.read_text()
    assert re.search(r"^- Status: fired$", text, re.MULTILINE)
    # Other fields untouched.
    assert "- Type: periodic" in text


def test_update_fields_with_empty_dict_is_noop(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section())
    before = p.read_text()

    update_fields(p, {})

    assert p.read_text() == before


def test_update_fields_handles_multiple_fields_per_job(tmp_path: Path) -> None:
    p = _write_jobs(tmp_path, _job_section())

    update_fields(
        p,
        {
            "user-greet-2026-04-28": {
                "Status": "done",
                "Execution result": "Greeted user successfully",
            }
        },
    )

    text = p.read_text()
    assert "- Status: done" in text
    assert "- Execution result: Greeted user successfully" in text


def test_update_fields_handles_multiple_jobs(tmp_path: Path) -> None:
    p = _write_jobs(
        tmp_path,
        _job_section(job_id="job-a"),
        _job_section(job_id="job-b"),
    )

    update_fields(
        p,
        {
            "job-a": {"Status": "fired"},
            "job-b": {"Status": "cancel"},
        },
    )

    text = p.read_text()
    # Each job's field is set independently — anchor on the section.
    a_section = re.search(r"## job-a.*?(?=## |$)", text, re.DOTALL).group(0)
    b_section = re.search(r"## job-b.*?(?=## |$)", text, re.DOTALL).group(0)
    assert "- Status: fired" in a_section
    assert "- Status: cancel" in b_section


def test_update_fields_raises_when_target_field_does_not_exist(
    tmp_path: Path,
) -> None:
    p = _write_jobs(tmp_path, _job_section())

    with pytest.raises(
        ValueError, match=r"^user-greet-2026-04-28: field '- Garbage:' not found",
    ):
        update_fields(p, {"user-greet-2026-04-28": {"Garbage": "x"}})


# ---------- purge_stale ----------


def test_purge_stale_removes_terminal_jobs_older_than_window(
    tmp_path: Path,
) -> None:
    old = _job_section(
        job_id="old-done",
        status="done",
        next_fire_time=NEVER,
        execution_time="2026-04-01T00:00",  # > 7 days before "now"
        last_fire_time="2026-04-01T00:00",
    )
    p = _write_jobs(tmp_path, old)

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    assert purged == ["old-done"]
    # The file must end up empty (no XX placeholder, no leftover content)
    # — kills both the substitution-string and the cleanup-regex
    # mutations in `_remove_sections`.
    assert p.read_text() == ""


def test_purge_stale_keeps_other_jobs_when_purging_one(tmp_path: Path) -> None:
    # Multi-section purge: ensures the cleanup regex on triple+ blank
    # lines doesn't leave XX placeholders in the file and that the
    # surviving job remains intact.
    p = _write_jobs(
        tmp_path,
        _job_section(
            job_id="purge-me",
            status="done",
            next_fire_time=NEVER,
            execution_time="2026-04-01T00:00",
            last_fire_time="2026-04-01T00:00",
        ),
        _job_section(job_id="keep-me"),
    )

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    text = p.read_text()
    assert purged == ["purge-me"]
    assert "## purge-me" not in text
    assert "## keep-me" in text
    assert "XX" not in text


def test_purge_stale_at_exactly_seven_days_old_is_purged(tmp_path: Path) -> None:
    # `>= _PURGE_AFTER` (7 days). Exactly 7 days must purge; mutating
    # to `>` would keep the boundary case alive.
    p = _write_jobs(
        tmp_path,
        _job_section(
            job_id="boundary-done",
            status="done",
            next_fire_time=NEVER,
            execution_time="2026-04-21T00:00",
            last_fire_time="2026-04-21T00:00",
        ),
    )

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    assert purged == ["boundary-done"]


def test_purge_stale_continues_past_non_terminal_jobs_to_purge_later_terminal(
    tmp_path: Path,
) -> None:
    # The `if status not in TERMINAL_STATUSES: continue` must NOT be
    # `break` — a pend (non-terminal) job ahead of a terminal-old job
    # would otherwise mask the latter.
    pend = Job(
        id="alive-pend",
        kind=KIND_PERIODIC,
        schedule="* * * * *",
        description="d",
        status=STATUS_PEND,
        next_fire_time="2026-04-29T07:00",
    )
    old_done = Job(
        id="old-done",
        kind=KIND_PERIODIC,
        schedule="* * * * *",
        description="d",
        status=STATUS_DONE,
        execution_time="2026-04-01T00:00",
    )
    # Use the preloaded-jobs path so we control the order exactly.
    p = tmp_path / "jobs.md"
    p.write_text("")  # exists but empty; jobs supplied via param

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p, jobs=[pend, old_done])

    assert purged == ["old-done"]


def test_purge_stale_logs_summary_when_jobs_are_purged(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    # Anchor the log message — kills the XX-wrap on the format string.
    section = _job_section(
        job_id="logged-purge",
        status="done",
        next_fire_time=NEVER,
        execution_time="2026-04-01T00:00",
        last_fire_time="2026-04-01T00:00",
    )
    p = _write_jobs(tmp_path, section)

    import logging
    with caplog.at_level(logging.INFO, logger="physiclaw.agent.engine.job_store"):
        with freeze_time("2026-04-28T00:00"):
            purge_stale(p)

    assert any(
        r.getMessage().startswith("jobs: purged 1 stale job(s):")
        and "logged-purge" in r.getMessage()
        for r in caplog.records
    )


def test_purge_stale_keeps_recent_terminal_jobs(tmp_path: Path) -> None:
    young = _job_section(
        job_id="young-done",
        status="done",
        next_fire_time=NEVER,
        execution_time="2026-04-26T00:00",  # < 7 days before "now"
        last_fire_time="2026-04-26T00:00",
    )
    p = _write_jobs(tmp_path, young)

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    assert purged == []
    assert "young-done" in p.read_text()


def test_purge_stale_keeps_non_terminal_jobs_regardless_of_age(
    tmp_path: Path,
) -> None:
    p = _write_jobs(
        tmp_path,
        _job_section(
            job_id="ancient-pend",
            status="pend",
            next_fire_time="2026-04-29T07:00",
            last_fire_time="2026-01-01T00:00",
            execution_time="2026-01-01T00:00",
        ),
    )

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    assert purged == []


def test_purge_stale_removes_terminal_with_no_parseable_timestamp(
    tmp_path: Path,
) -> None:
    # done/cancel/fail with no execution_time and no last_fire_time —
    # treated as "no timestamp" and purged regardless of age.
    p = _write_jobs(
        tmp_path,
        _job_section(
            job_id="ghost-done",
            status="done",
            next_fire_time=NEVER,
            last_fire_time=NEVER,
            execution_time=NEVER,
        ),
    )

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    assert purged == ["ghost-done"]


def test_purge_stale_returns_empty_when_file_missing(tmp_path: Path) -> None:
    assert purge_stale(tmp_path / "missing.md") == []


def test_purge_stale_returns_empty_when_file_unparseable(tmp_path: Path) -> None:
    p = tmp_path / "jobs.md"
    p.write_text("## bad-job\n- Type: hourly\n")  # malformed → ValueError

    assert purge_stale(p) == []


def test_purge_stale_falls_through_to_last_fire_time_when_execution_time_unparseable(
    tmp_path: Path,
) -> None:
    # _latest_timestamp tries execution_time first; on ValueError it
    # continues to last_fire_time. Validates the fall-through branch.
    section = _job_section(
        job_id="bad-exec-ts",
        status="done",
        next_fire_time=NEVER,
        execution_time="not iso",  # bad — fromisoformat raises
        last_fire_time="2026-04-01T00:00",  # valid + > 7 days old
    )
    p = _write_jobs(tmp_path, section)

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    assert purged == ["bad-exec-ts"]


def test_purge_stale_uses_module_JOBS_PATH_when_path_argument_omitted() -> None:
    # JOBS_PATH captured at import time; without a real file there, the
    # function returns [] safely.
    assert purge_stale() == []


def test_purge_stale_accepts_explicit_now_argument(tmp_path: Path) -> None:
    section = _job_section(
        job_id="caller-time",
        status="done",
        next_fire_time=NEVER,
        execution_time="2026-04-01T00:00",
        last_fire_time="2026-04-01T00:00",
    )
    p = _write_jobs(tmp_path, section)

    purged = purge_stale(p, now=dt.datetime(2026, 4, 28))

    assert purged == ["caller-time"]


def test_purge_stale_uses_dt_datetime_now_when_now_argument_omitted(
    tmp_path: Path,
) -> None:
    # Without `now=`, the function reads the wall clock; freezegun makes
    # that deterministic.
    section = _job_section(
        job_id="ancient-done",
        status="done",
        next_fire_time=NEVER,
        execution_time="2020-01-01T00:00",
        last_fire_time="2020-01-01T00:00",
    )
    p = _write_jobs(tmp_path, section)

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p)

    assert purged == ["ancient-done"]


def test_purge_stale_uses_preloaded_jobs_list_when_supplied(
    tmp_path: Path,
) -> None:
    # The cron hook passes a pre-loaded jobs list to avoid re-parsing.
    # File on disk says one thing; the supplied list says another. The
    # supplied list wins for the staleness check.
    p = _write_jobs(
        tmp_path,
        _job_section(
            job_id="from-disk",
            status="done",
            next_fire_time=NEVER,
            execution_time="2026-04-26T00:00",  # young — wouldn't purge
            last_fire_time="2026-04-26T00:00",
        ),
    )
    preloaded = [
        Job(
            id="from-disk",
            kind=KIND_PERIODIC,
            schedule="0 7 * * *",
            description="d",
            status=STATUS_DONE,
            execution_time="2026-04-01T00:00",  # old per the supplied list
        )
    ]

    with freeze_time("2026-04-28T00:00"):
        purged = purge_stale(p, jobs=preloaded)

    assert purged == ["from-disk"]
