"""Contract tests for `physiclaw.agent.engine.dto`.

Covers what the engine relies on: frozen-ness of immutable DTOs,
default-factory isolation on AssistantMessage, the `ToolResult` legacy
alias, and FinishReason wire-string values. Plain-storage round-trips
are not tested directly (autogenerated by `@dataclass`); we exercise
field storage through behavior tests like `tool_names()` instead.

Accepted mutmut survivor: `ContentBlock = Union[TextBlock, ImageBlock]`
mutated to `ContentBlock = None`. This name is referenced only inside
type annotations (`UserMessage.content: str | list[ContentBlock]`),
never at runtime, so behavior is unaffected. Killing the mutant would
require importing it for `typing.get_args` introspection — not worth
the test for a type alias.
"""
from __future__ import annotations

import dataclasses
import typing

import pytest

from physiclaw.agent.engine.dto import (
    AssistantMessage,
    FinishReason,
    ImageBlock,
    Message,
    SystemMessage,
    TextBlock,
    ToolCall,
    ToolResult,
    ToolResultMessage,
    Usage,
    UserMessage,
)


@pytest.mark.parametrize(
    "member, expected",
    [
        (FinishReason.TOOL_CALLS, "tool_calls"),
        (FinishReason.STOP, "stop"),
        (FinishReason.LENGTH, "length"),
        (FinishReason.CONTENT_FILTER, "content_filter"),
        (FinishReason.ERROR, "error"),
    ],
)
def test_finish_reason_value_equals_string_form(
    member: FinishReason, expected: str
) -> None:
    assert member == expected
    assert member.value == expected


@pytest.mark.parametrize(
    "instance, attr, value",
    [
        (TextBlock(text="x"), "text", "y"),
        (ImageBlock(media_type="image/png", data_b64="aGk="), "data_b64", "bw=="),
        (ToolCall(id="t1", name="f", arguments={}), "id", "t2"),
        (Usage(), "prompt_tokens", 99),
        (SystemMessage(content="x"), "content", "y"),
        (UserMessage(content="x"), "content", "y"),
        (
            ToolResultMessage(tool_call_id="t1", content="ok"),
            "is_error",
            True,
        ),
    ],
)
def test_dto_frozen_dataclass_rejects_mutation(instance, attr, value) -> None:
    with pytest.raises(dataclasses.FrozenInstanceError):
        setattr(instance, attr, value)


def test_assistant_message_is_not_frozen() -> None:
    msg = AssistantMessage(
        content="x", tool_calls=[], finish_reason=FinishReason.STOP
    )

    msg.content = "y"

    assert msg.content == "y"


def test_usage_default_is_all_zero() -> None:
    u = Usage()

    assert (
        u.prompt_tokens,
        u.completion_tokens,
        u.cached_tokens,
        u.cache_creation_tokens,
    ) == (0, 0, 0, 0)


def test_assistant_message_default_usage_is_zero_filled() -> None:
    msg = AssistantMessage(
        content="x", tool_calls=[], finish_reason=FinishReason.STOP
    )

    assert msg.usage == Usage()


def test_assistant_message_default_factories_not_shared_between_instances() -> None:
    a = AssistantMessage(
        content="", tool_calls=[], finish_reason=FinishReason.STOP
    )
    b = AssistantMessage(
        content="", tool_calls=[], finish_reason=FinishReason.STOP
    )

    a.raw["mutated"] = True
    a.vendor_extra["x"] = 1

    assert b.raw == {}
    assert b.vendor_extra == {}


def test_assistant_message_tool_names_returns_names_in_call_order() -> None:
    calls = [
        ToolCall(id="1", name="alpha", arguments={}),
        ToolCall(id="2", name="beta", arguments={"k": 1}),
        ToolCall(id="3", name="alpha", arguments={}),
    ]
    msg = AssistantMessage(
        content="", tool_calls=calls, finish_reason=FinishReason.TOOL_CALLS
    )

    assert msg.tool_names() == ["alpha", "beta", "alpha"]


def test_assistant_message_tool_names_empty_when_no_tool_calls() -> None:
    msg = AssistantMessage(
        content="x", tool_calls=[], finish_reason=FinishReason.STOP
    )

    assert msg.tool_names() == []


def test_tool_result_message_defaults_are_not_error_not_superseded() -> None:
    r = ToolResultMessage(tool_call_id="t1", content="ok")

    assert r.is_error is False
    assert r.is_superseded is False


def test_tool_result_is_alias_for_tool_result_message() -> None:
    # dto.py marks `ToolResult = ToolResultMessage` as a legacy alias kept
    # alive for fixture-only callers; the alias must be the same object,
    # not a subclass.
    assert ToolResult is ToolResultMessage


@pytest.mark.parametrize(
    "content",
    [
        "plain text",
        [
            TextBlock(text="hi"),
            ImageBlock(media_type="image/jpeg", data_b64="aGk="),
        ],
    ],
)
def test_user_message_accepts_string_or_block_list(content) -> None:
    msg = UserMessage(content=content)

    assert msg.content == content


def test_message_union_includes_all_four_kinds() -> None:
    args = set(typing.get_args(Message))

    assert args == {SystemMessage, UserMessage, AssistantMessage, ToolResultMessage}
