"""PhysiClaw's single data root.

All persistent state — calibration, memory, jobs, model cache, logs —
lives under ``~/.physiclaw/``. Override with ``PHYSICLAW_HOME`` (read once
at import, so set it *before* the first ``import physiclaw`` in tests).

Layout::

    ~/.physiclaw/
    ├── calibration/{bundle.json, cache/}
    ├── memory/{memory.md, USER.md, YYYY-MM-DD.md}
    ├── jobs/jobs.md
    ├── models/omniparser_icon_detect/model.onnx
    ├── skills/<name>/SKILL.md           (user-authored; overrides bundled)
    ├── ui-presets/system-keyboard.md    (generated by `setup phone`)
    ├── snapshots/, screenshots/, tool_calls/
    ├── run/server.json                  (live server pid+host+port; cleared on exit)
    └── log/{claude/, engine/}
"""

import json
import os
from pathlib import Path

HOME: Path = Path(os.environ.get("PHYSICLAW_HOME", "~/.physiclaw")).expanduser()
LOG_DIR: Path = HOME / "log"


def ensure_dirs() -> None:
    """Create HOME and LOG_DIR. Safe to call repeatedly."""
    HOME.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)


def model_cache() -> Path:
    return HOME / "models"


def omniparser_onnx() -> Path:
    return model_cache() / "omniparser_icon_detect" / "model.onnx"


def calibration_bundle() -> Path:
    return HOME / "calibration" / "bundle.json"


def load_calibration_bundle() -> dict | None:
    """Read+parse ``calibration/bundle.json``. None on missing/unreadable/invalid."""
    p = calibration_bundle()
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text())
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def calibration_cache_dir() -> Path:
    return HOME / "calibration" / "cache"


def snapshots_dir() -> Path:
    return HOME / "snapshots"


def screenshots_dir() -> Path:
    return HOME / "screenshots"


def tool_calls_dir() -> Path:
    return HOME / "tool_calls"


def jobs_file() -> Path:
    return HOME / "jobs" / "jobs.md"


def memory_dir() -> Path:
    return HOME / "memory"


def skills_dir() -> Path:
    return HOME / "skills"


def ui_presets_dir() -> Path:
    return HOME / "ui-presets"


def runtime_state_file() -> Path:
    return HOME / "run" / "server.json"


def claude_log_dir() -> Path:
    return LOG_DIR / "claude"


def engine_log_dir() -> Path:
    return LOG_DIR / "engine"
